name: Terraform Plan

on:
  pull_request:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.8.5

      - name: Terraform Format Check
        run: terraform fmt -check -recursive

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: "6f684002-5e6b-46a0-860f-117435208139"
          client-secret: ${{ secrets.AZURE_CLIENT_SECRET }}
          tenant-id: "d73b8547-0c7c-4052-98a9-e6e952273a62"
          subscription-id: "3db1461e-a110-4c9d-b193-6df37b3a4a76"

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan -out=tfplan

      - name: Upload Terraform Plan
        uses: actions/upload-artifact@v4
        with:
          name: terraform-plan
          path: tfplan    
          # trigger workflow    

